import type { Metadata } from "next";
import {League_Spartan} from 'next/font/google';
import "/public/globals.css";
import Navbar from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import ToTop from "@/components/toTopButton";

const league_spartan=League_Spartan({
  subsets:['latin'],
  weight:['100','400','700','900'],
  variable:'--font-league_spartan',
})

export const metadata: Metadata = {
  title: "TipTank - evolutionize Rewards with Decentralized Tipping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${league_spartan.variable} antialiased bg-[#00302e]`} 
      >
        {/* <Navbar/> */}
        <nav><Navbar/></nav>      
        {children}
        <ToTop/>
        <footer><Footer/></footer>
      </body>
    </html>
  );
}
